package common;

public enum Command {
    SIGN_IN, SIGN_UP, POSTING, REPOST, GET_REPOST_MEMBERS, EDIT_PROFILE, LOG_OUT, UNIQUE_USER, GET_POSTS, GET_MY_POSTS,
    GET_USERS, LIKE, UNLIKE, LIKE_MEMBERS, LIKE_REPOST_COMMENT_NUMBERS, COMMENT, COMMENT_NUMBERS, FOLLOW, UNFOLLOW,
    GET_FOLLOWER_MEMBERS, GET_FOLLOWING_MEMBERS, GET_INFO, FORGOT_PASSWORD, GET_TIMELINE
}
